### PR TITLE
Update routes.rb

### PR DESCRIPTION
**Pull request by vincentstoop**
Routes in routes.rb gezet.

### CODE REVIEW

**Comment by KellyHuliselan** [comment]
Okay

**Comment by mhzehl** [comment]
@vincentstoop Looking at the Codaisseurbnb example, shouldn't we add a resources :users as well?

**Comment by vincentstoop** [comment]
@mhzehl true. adapted the file here.

**Comment by mhzehl** [comment]
Great, merge time! ;)

**Pull request merged**
